name: Generate Sdk

on:
  push:
    branches:
      - develop

jobs:
  generate:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install global tools
        run: |
          npm install

      - name: Generate files
        run: |
          npm run client:generate -- -i ${{ vars.SWAGGER_DOCS_URL }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d.%H%M%S')"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOPPASS_ACCESS_TOKEN }}
          commit-message: 'release: generate release ${{ steps.date.outputs.date }}'
          committer: Redhouane Sobaihi <redouane.sobaihi@live.com>
          author: Redhouane Sobaihi <redouane.sobaihi@live.com>
          branch: release/${{ steps.date.outputs.date }}
          base: develop
          delete-branch: true
          title: Release ${{ steps.date.outputs.date }}
          body: |
            Merge release `${{ steps.date.outputs.date }}` to main
          labels: |
            Release